### PR TITLE
Fix small typos in docs

### PR DESCRIPTION
**Pull request by sotte**
Also be consistent about usage of `tf-encrypted` vs TF Encrypted.

### CODE REVIEW

**Comment by mortendahl** [comment]
Hi @sotte, thanks for putting this together! We've moved to `TF Encrypted` instead to `tf-encrypted` but as you point out we have missed a few places.

**Comment by sotte** [comment]
My bad, I had the impression `tf-encrypted` was still the majority. I'll fix it everywhere then as I'm reading the docs anyway.

**Comment by mortendahl** [comment]
That would be amazing!

**Comment by mortendahl** [comment]
Hi @sotte, I'd be happy to help you close this one up -- want to give me push access to your local branch and I'll add a commit with the changes above?

**Comment by sotte** [comment]
@mortendahl I actually fixed it, but forgot to force push :( Sorry about that!

**Comment by mortendahl** [comment]
thanks of a lot @sotte, good catches!

**Comment by sotte** [comment]
Thank you!

**Pull request merged**
