### PR TITLE
stub instructions

### PR DESCRIPTION
**Pull request by bendecoste**
See README diff for examples on how this actually gets used.

### CODE REVIEW

**Comment by bendecoste** [comment]
> Looks good, stubs/numpy/init.pyi is empty. It should probably be removed?

Left it in there so it is more obvious how to setup a new library whenever the time comes .. I don't think it's a big deal to sit there.

**Comment by justin1121** [comment]
If `MYPYPATH` is set to the stubs folder any code that uses numpy, mypy will complain about it not being able to find that attribute in the numpy module.

image

**Comment by justin1121** [comment]
Could just do a test package instead or something!

**Comment by bendecoste** [comment]
> If MYPYPATH is set to the stubs folder any code that uses numpy, mypy will complain about it not being able to find that attribute in the numpy module.

pretty sure that is because the ini file is empty.  We should probably use the official one anyway! You're saying rename `numpy` in stubs to something like `example`?

**Comment by justin1121** [comment]
Yeah! I'd be fine with that or just putting the official one in our repo some how.

**Comment by bendecoste** [comment]
> Yeah! I'd be fine with that or just putting the official one in our repo some how.

Thought about doing that but i think we'd have to use submodules which i'm not a huge fan of

**Pull request merged**
